services:
    nginx:
        container_name: nginx
        image: nginx:inception
        build:
            context: ./nginx
            args:
                - MAINTAINER
                - SSL_PATH
                - FQDN
        restart: always
        volumes: 
            - front-vol:/var/www
        ports: 
            - "443:443"
        init: true
        env_file: ".env"
        profiles:
           - mandatory
           - bonus
        networks:
            - entrypoint-tier
            - front-tier
        #depends_on:
            #- wordpress

              #    mariadb:
              #        container_name: mariadb
              #        image: srcs/mariadb
              #        build:
              #            context: srcs/mariadb
              #        restart: always
              #        volumes: 
              #            - back-vol:/srv/
              #        ports: "3306:3306"
              #        depends_on:
              #            - nginx
              #            - wordpress
              #        init: true
              #        profiles:
              #            - mandatory
              #            - bonus
              #        networks:
              #            - back-tier

    wordpress:
        container_name: wordpress
        image: wordpress:inception
        build:
            context: wordpress
            args:
                - MAINTAINER
        restart: always
        volumes: 
            - front-vol:/var/www
        ports: 
            - "9000:9000"
        profiles:
            - mandatory
        networks:
            #- entrypoint-tier
            - front-tier
            #- back-tier
        env_file: ".env"


networks:
    entrypoint-tier:
        attachable: true
    front-tier:
        attachable: true
        #    back-tier:
        #attachable: true

volumes:
    front-vol:
        name: front-vol
        driver_opts:
            type: "nfs"
            o: bind
            device: $HOME/data/front-vol
        #mountpoint: /$HOME/data/front-vol
        # - /home/$USER/data/front-vol
        # back-vol:
        # - /home/$USER/data/back-vol

        #configs:
        #nginx-config:
        #- ./srcs/nginx/config

        #secrets:
        #server-certificate:
        #file: srcs/nginx/config/server.cert

        #profiles:
        #mandatory:
        #bonus:
