services:
    nginx:
        container_name: nginx
        image: nginx:inception
        build:
            context: ./nginx
            args:
                - MAINTAINER
                - CA_PATH
                - CA_KEY_PATH
                - CA_CRT_PATH
                - CA_NEWCRT_PATH
                - CA_CONFIG_PATH
                - CA_CONFIG
                - CA_SERIAL
                - CA_INDEX
                - CA_KEY
                - CA_CSR
                - CA_CRT
                - CA_C
                - CA_ST
                - CA_L
                - CA_O
                - CA_OU
                - CA_CN
                - CA_EMAIL
                - SSL_PATH
                - SSL_KEY
                - SSL_CSR
                - SSL_CRT
                - SSL_DER
                - SSL_OU
                - FQDN
        restart: always
        volumes: 
            - front-vol:/var/www/data
        ports: 
            - "443:443"
        init: true
        env_file: ".env"
        profiles:
           - mandatory
           - bonus
        networks:
            - entrypoint-tier

              #    mariadb:
              #        container_name: mariadb
              #        image: srcs/mariadb
              #        build:
              #            context: srcs/mariadb
              #        restart: always
              #        volumes: 
              #            - back-vol:/srv/
              #        ports: "3306:3306"
              #        depends_on:
              #            - nginx
              #            - wordpress
              #        init: true
              #        profiles:
              #            - mandatory
              #            - bonus
              #        networks:
              #            - back-tier

              #    wordpress:
              #        container_name: wordpress
              #        image: srcs/wordpress
              #        build:
              #            context: srcs/wordpress
              #        restart: always
              #        volumes: 
              #            - front-vol:/var/www/html
              #        ports: "9000:9000"
              #        depends_on:
              #            - nginx
              #        init: true
              #        profiles:
              #            - mandatory
              #        networks:
              #            - front-tier
              #            - back-tier


networks:
    entrypoint-tier:
        attachable: true
        #front-tier:
        #attachable: true
        #    back-tier:
        #attachable: true

volumes:
    front-vol:
        name: front-vol
        driver_opts:
            type: "nfs"
            o: bind
            device: $HOME/data/front-vol
        #mountpoint: /$HOME/data/front-vol
        # - /home/$USER/data/front-vol
        # back-vol:
        # - /home/$USER/data/back-vol

        #configs:
        #nginx-config:
        #- ./srcs/nginx/config

        #secrets:
        #server-certificate:
        #file: srcs/nginx/config/server.cert

        #profiles:
        #mandatory:
        #bonus:
